### ISSUE TITLE
Is there a way to end prematurely my StateM test?

### ISSUE THREAD

**Issue by sebastienatplumbee** [proper-testing/proper#149]
Hi,

I am using it currently to test a card game. Sometimes I end up in a situation where the game is over and everything is fine but more commands will be applied.
I wonder if there is a call to make or a specific value to return to let the framework know that it can stop now and take it as a success.

Thanks

**Comment by robertoaloi** [comment]
Hi, I guess you could model the end of the game as a boolean flag (e.g. `game_ended`) in the state of your _statem_. You would set the flag to `false` in the `initial_state()` function, change it to `true` in one of the `next_state` function when the end of the end of the game is reached and check the value flag in the appropriate `precondition` functions so that commands are not included in the sequence once the end of the game is reached (i.e. once the flag is set to `true`).

**Comment by svarlet** [comment]
Makes sense thank you

**Comment by robertoaloi** [comment]
@kostis I guess this can be closed as a (solved) usage question and not a proper issue?

**Comment by kostis** [comment]
Yes, closing -- thanks for your reply.
