### ISSUE TITLE
share state between transition of proper_fsm

### ISSUE THREAD

**Issue by 0xAX** [proper-testing/proper#180]
Hello,

I'm trying to write simple test with `proper_fsm` and I need to share state between transitions.
My example using Elixir and propcheck but it is just wrapper around `proper_fsm`:

```Elixir
  property "test",  [:verbose] do
    forall cmds <- commands(__MODULE__) do
      {history, state, result} = run_commands(__MODULE__, cmds)
      (result == :ok)
      |> aggregate(command_names(cmds))
      |> when_fail(
        :io.format("History: ~p~nState: ~p~nResult: ~p~n", [history, state, result])
      )
    end
  end

  def initial_state() do
    :detached
  end

  def initial_state_data() do
    %{count: 0}
  end

  def detached(state) do
    [{:attached, {:call, __MODULE__, :exec, [:attach, user(), state]}}]
  end
  def attached(state) do
    [{:access, {:call, __MODULE__, :exec, [:access, state]}}]
  end
  def access(state), do: [{:attached, {:call, __MODULE__, :exec, [:attach, user(), state]}}]

  def exec(:attach, user, state) do
    # do some stuff .....
    %{}
  end
  
  def exec(:access, state) do
    :io.format("state in access - ~p~n", [state])
    state
  end
  
  def precondition(from, target, state_data, call) do
    true
  end
  
  def postcondition(from, target, state_data, call, result) do
    true
  end

  def next_state_data(:detached, :attached, state, result, call) when is_map(result) do
    Map.put(state, :count, 1)
  end
  def next_state_data(from, target, state_data, result, call) do
    state_data
  end
```

After `exec(:attach, user, state)` is executed the `count` is updated in the `next_state_data`, so I'm expecting to see `count = 1` in the ``, but I see `%{count: 0}` instead. Did I misunderstand something in proper_fsm logic or it is kind of a bug?

Thank you

**Comment by kostis** [comment]
Sorry but I am closing this.  Prop*Er* is for *Er*lang.

If you want an answer, either submit this to the propcheck repo or open a new issue here with some _self-contained_ _Erlang_ example that shows the issue/problem you are experiencing. Also, make sure the example code is such that it can be run on its own (so that we can easily debug it and possibly add it to the PropEr tests if this turns out to be a bug) and specify the behavior you would have expected to see instead.
